
CREATE TABLE IF NOT EXISTS ads (
  id            INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         VARCHAR(155) NOT NULL,
  type          TEXT NOT NULL,
  area_place_id TEXT NOT NULL,
  area_label    TEXT NOT NULL,
  price         INTEGER NOT NULL,
  description   TEXT NULL, 
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT ads_type_chk CHECK (type IN ('Rent', 'Buy', 'Exchange', 'Donation')),
  CONSTRAINT ads_price_non_negative_chk CHECK (price >= 0)
);

